trigger: none

pool:rksteel-local-pool
  
jobs:
  - job: terraforminitplan
    displayName: Terraform init and plan execution
    steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'rksteel-dev-conn'
          backendAzureRmOverrideSubscriptionID: 'c94a57a8-66ad-4fe4-9d9d-e061aafd17c0'
          backendAzureRmResourceGroupName: 'rg-state'
          backendAzureRmStorageAccountName: 'statefilestore454'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'rk.dev.tfstate'

          