trigger: none

pool: rksteel-local-pool
  


steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'infrapipeline_sc'
    backendAzureRmResourceGroupName: 'rg-state'
    backendAzureRmStorageAccountName: 'statefilestore454'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'dev.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'infrapipeline_sc'

- task: ManualValidation@1
  inputs:
    notifyUsers: 'veloran@zohomail.in'
    approvers: 'veloran@zohomail.in'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'infrapipeline_sc'